// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class AppHubLogging: AppHubStub {
    let inner: any AppHubStub
    let logger: Logger

    public init(_ inner: any AppHubStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-apphub-v1"
      logger[metadataKey: "gcp.client.service"] = "apphub"
      logger[metadataKey: "gcp.experimental.swift.client"] = "AppHub"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func lookupServiceProjectAttachment(
      request: LookupServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "lookupServiceProjectAttachment",
        action: {
          (r: LookupServiceProjectAttachmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse
          in
          return try await self.inner.lookupServiceProjectAttachment(request: r, options: o)
        })
    }

    public func listServiceProjectAttachments(
      request: ListServiceProjectAttachmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceProjectAttachments",
        action: {
          (r: ListServiceProjectAttachmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse
          in
          return try await self.inner.listServiceProjectAttachments(request: r, options: o)
        })
    }

    public func createServiceProjectAttachment(
      request: CreateServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceProjectAttachment",
        action: {
          (r: CreateServiceProjectAttachmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServiceProjectAttachment(request: r, options: o)
        })
    }

    public func getServiceProjectAttachment(
      request: GetServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ServiceProjectAttachment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceProjectAttachment",
        action: {
          (r: GetServiceProjectAttachmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.ServiceProjectAttachment
          in
          return try await self.inner.getServiceProjectAttachment(request: r, options: o)
        })
    }

    public func deleteServiceProjectAttachment(
      request: DeleteServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteServiceProjectAttachment",
        action: {
          (r: DeleteServiceProjectAttachmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServiceProjectAttachment(request: r, options: o)
        })
    }

    public func detachServiceProjectAttachment(
      request: DetachServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "detachServiceProjectAttachment",
        action: {
          (r: DetachServiceProjectAttachmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse
          in
          return try await self.inner.detachServiceProjectAttachment(request: r, options: o)
        })
    }

    public func listDiscoveredServices(
      request: ListDiscoveredServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDiscoveredServices",
        action: {
          (r: ListDiscoveredServicesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse
          in
          return try await self.inner.listDiscoveredServices(request: r, options: o)
        })
    }

    public func getDiscoveredService(
      request: GetDiscoveredServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.DiscoveredService {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDiscoveredService",
        action: {
          (r: GetDiscoveredServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.DiscoveredService
          in
          return try await self.inner.getDiscoveredService(request: r, options: o)
        })
    }

    public func lookupDiscoveredService(
      request: LookupDiscoveredServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "lookupDiscoveredService",
        action: {
          (r: LookupDiscoveredServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse
          in
          return try await self.inner.lookupDiscoveredService(request: r, options: o)
        })
    }

    public func listServices(
      request: ListServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServices",
        action: {
          (r: ListServicesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.ListServicesResponse
          in
          return try await self.inner.listServices(request: r, options: o)
        })
    }

    public func createService(
      request: CreateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createService",
        action: {
          (r: CreateServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createService(request: r, options: o)
        })
    }

    public func getService(
      request: GetServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.Service {
      try await self._intercept(
        request: request,
        options: options,
        name: "getService",
        action: {
          (r: GetServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.Service
          in
          return try await self.inner.getService(request: r, options: o)
        })
    }

    public func updateService(
      request: UpdateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateService",
        action: {
          (r: UpdateServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateService(request: r, options: o)
        })
    }

    public func deleteService(
      request: DeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteService",
        action: {
          (r: DeleteServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteService(request: r, options: o)
        })
    }

    public func listDiscoveredWorkloads(
      request: ListDiscoveredWorkloadsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDiscoveredWorkloads",
        action: {
          (r: ListDiscoveredWorkloadsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse
          in
          return try await self.inner.listDiscoveredWorkloads(request: r, options: o)
        })
    }

    public func getDiscoveredWorkload(
      request: GetDiscoveredWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.DiscoveredWorkload {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDiscoveredWorkload",
        action: {
          (r: GetDiscoveredWorkloadRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.DiscoveredWorkload
          in
          return try await self.inner.getDiscoveredWorkload(request: r, options: o)
        })
    }

    public func lookupDiscoveredWorkload(
      request: LookupDiscoveredWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "lookupDiscoveredWorkload",
        action: {
          (r: LookupDiscoveredWorkloadRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse
          in
          return try await self.inner.lookupDiscoveredWorkload(request: r, options: o)
        })
    }

    public func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListWorkloadsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listWorkloads",
        action: {
          (r: ListWorkloadsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.ListWorkloadsResponse
          in
          return try await self.inner.listWorkloads(request: r, options: o)
        })
    }

    public func createWorkload(
      request: CreateWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createWorkload",
        action: {
          (r: CreateWorkloadRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createWorkload(request: r, options: o)
        })
    }

    public func getWorkload(
      request: GetWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.Workload {
      try await self._intercept(
        request: request,
        options: options,
        name: "getWorkload",
        action: {
          (r: GetWorkloadRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.Workload
          in
          return try await self.inner.getWorkload(request: r, options: o)
        })
    }

    public func updateWorkload(
      request: UpdateWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateWorkload",
        action: {
          (r: UpdateWorkloadRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateWorkload(request: r, options: o)
        })
    }

    public func deleteWorkload(
      request: DeleteWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteWorkload",
        action: {
          (r: DeleteWorkloadRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteWorkload(request: r, options: o)
        })
    }

    public func listApplications(
      request: ListApplicationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListApplicationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listApplications",
        action: {
          (r: ListApplicationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.ListApplicationsResponse
          in
          return try await self.inner.listApplications(request: r, options: o)
        })
    }

    public func createApplication(
      request: CreateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createApplication",
        action: {
          (r: CreateApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createApplication(request: r, options: o)
        })
    }

    public func getApplication(
      request: GetApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.Application {
      try await self._intercept(
        request: request,
        options: options,
        name: "getApplication",
        action: {
          (r: GetApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudAppHubV1.Application
          in
          return try await self.inner.getApplication(request: r, options: o)
        })
    }

    public func updateApplication(
      request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateApplication",
        action: {
          (r: UpdateApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateApplication(request: r, options: o)
        })
    }

    public func deleteApplication(
      request: DeleteApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteApplication",
        action: {
          (r: DeleteApplicationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteApplication(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
