// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The App Hub API allows you to manage App Hub resources.
///
/// @Snippet(path: "AppHubQuickstart")
public final class AppHubClient: Clients.AppHubProtocol, Sendable {
  let inner: any Clients.AppHubStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `AppHubClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.AppHubStub = try Clients.AppHubTransport(options)
    inner = Clients.AppHubRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AppHubLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists a service project attachment for a given service project. You can
  /// call this API from any project to find if it is attached to a host project.
  ///
  /// @Snippet(path: "AppHub_LookupServiceProjectAttachment")
  public func lookupServiceProjectAttachment(
    request: LookupServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse {
    try await self.inner.lookupServiceProjectAttachment(request: request, options: options)
  }

  /// Lists service projects attached to the host project.
  ///
  /// @Snippet(path: "AppHub_ListServiceProjectAttachments")
  public func listServiceProjectAttachments(
    request: ListServiceProjectAttachmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse {
    try await self.inner.listServiceProjectAttachments(request: request, options: options)
  }

  /// Lists service projects attached to the host project.
  ///
  /// @Snippet(path: "AppHub_ListServiceProjectAttachments")
  public func listServiceProjectAttachments(
    byItem: ListServiceProjectAttachmentsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ServiceProjectAttachment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listServiceProjectAttachments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Attaches a service project to the host project.
  ///
  /// @Snippet(path: "AppHub_CreateServiceProjectAttachment")
  public func createServiceProjectAttachment(
    request: CreateServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createServiceProjectAttachment(request: request, options: options)
  }

  /// Attaches a service project to the host project.
  ///
  /// @Snippet(path: "AppHub_CreateServiceProjectAttachment")
  public func createServiceProjectAttachment(
    withPolling: CreateServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ServiceProjectAttachment> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ServiceProjectAttachment>.State in
      return try op._extractStatus(ServiceProjectAttachment.self)
    }
    let rawOp = try await self.createServiceProjectAttachment(
      request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ServiceProjectAttachment>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets a service project attachment.
  ///
  /// @Snippet(path: "AppHub_GetServiceProjectAttachment")
  public func getServiceProjectAttachment(
    request: GetServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ServiceProjectAttachment {
    try await self.inner.getServiceProjectAttachment(request: request, options: options)
  }

  /// Deletes a service project attachment.
  ///
  /// @Snippet(path: "AppHub_DeleteServiceProjectAttachment")
  public func deleteServiceProjectAttachment(
    request: DeleteServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteServiceProjectAttachment(request: request, options: options)
  }

  /// Deletes a service project attachment.
  ///
  /// @Snippet(path: "AppHub_DeleteServiceProjectAttachment")
  public func deleteServiceProjectAttachment(
    withPolling: DeleteServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteServiceProjectAttachment(
      request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Detaches a service project from a host project.
  /// You can call this API from any service project without needing access to
  /// the host project that it is attached to.
  ///
  /// @Snippet(path: "AppHub_DetachServiceProjectAttachment")
  public func detachServiceProjectAttachment(
    request: DetachServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse {
    try await self.inner.detachServiceProjectAttachment(request: request, options: options)
  }

  /// Lists Discovered Services that can be added to an Application in a host
  /// project and location.
  ///
  /// @Snippet(path: "AppHub_ListDiscoveredServices")
  public func listDiscoveredServices(
    request: ListDiscoveredServicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse {
    try await self.inner.listDiscoveredServices(request: request, options: options)
  }

  /// Lists Discovered Services that can be added to an Application in a host
  /// project and location.
  ///
  /// @Snippet(path: "AppHub_ListDiscoveredServices")
  public func listDiscoveredServices(
    byItem: ListDiscoveredServicesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<DiscoveredService, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDiscoveredServices(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a Discovered Service in a host project and location.
  ///
  /// @Snippet(path: "AppHub_GetDiscoveredService")
  public func getDiscoveredService(
    request: GetDiscoveredServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.DiscoveredService {
    try await self.inner.getDiscoveredService(request: request, options: options)
  }

  /// Lists a Discovered Service in a host project and location, with a
  /// given resource URI.
  ///
  /// @Snippet(path: "AppHub_LookupDiscoveredService")
  public func lookupDiscoveredService(
    request: LookupDiscoveredServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse {
    try await self.inner.lookupDiscoveredService(request: request, options: options)
  }

  /// Lists Services in an Application.
  ///
  /// @Snippet(path: "AppHub_ListServices")
  public func listServices(
    request: ListServicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListServicesResponse {
    try await self.inner.listServices(request: request, options: options)
  }

  /// Lists Services in an Application.
  ///
  /// @Snippet(path: "AppHub_ListServices")
  public func listServices(
    byItem: ListServicesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Service, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListServicesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listServices(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a Service in an Application.
  ///
  /// @Snippet(path: "AppHub_CreateService")
  public func createService(
    request: CreateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createService(request: request, options: options)
  }

  /// Creates a Service in an Application.
  ///
  /// @Snippet(path: "AppHub_CreateService")
  public func createService(
    withPolling: CreateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Service> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Service>.State in
      return try op._extractStatus(Service.self)
    }
    let rawOp = try await self.createService(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Service>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets a Service in an Application.
  ///
  /// @Snippet(path: "AppHub_GetService")
  public func getService(
    request: GetServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.Service {
    try await self.inner.getService(request: request, options: options)
  }

  /// Updates a Service in an Application.
  ///
  /// @Snippet(path: "AppHub_UpdateService")
  public func updateService(
    request: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateService(request: request, options: options)
  }

  /// Updates a Service in an Application.
  ///
  /// @Snippet(path: "AppHub_UpdateService")
  public func updateService(
    withPolling: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Service> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Service>.State in
      return try op._extractStatus(Service.self)
    }
    let rawOp = try await self.updateService(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Service>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a Service from an Application.
  ///
  /// @Snippet(path: "AppHub_DeleteService")
  public func deleteService(
    request: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteService(request: request, options: options)
  }

  /// Deletes a Service from an Application.
  ///
  /// @Snippet(path: "AppHub_DeleteService")
  public func deleteService(
    withPolling: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteService(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Discovered Workloads that can be added to an Application in a host
  /// project and location.
  ///
  /// @Snippet(path: "AppHub_ListDiscoveredWorkloads")
  public func listDiscoveredWorkloads(
    request: ListDiscoveredWorkloadsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse {
    try await self.inner.listDiscoveredWorkloads(request: request, options: options)
  }

  /// Lists Discovered Workloads that can be added to an Application in a host
  /// project and location.
  ///
  /// @Snippet(path: "AppHub_ListDiscoveredWorkloads")
  public func listDiscoveredWorkloads(
    byItem: ListDiscoveredWorkloadsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<DiscoveredWorkload, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDiscoveredWorkloads(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a Discovered Workload in a host project and location.
  ///
  /// @Snippet(path: "AppHub_GetDiscoveredWorkload")
  public func getDiscoveredWorkload(
    request: GetDiscoveredWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.DiscoveredWorkload {
    try await self.inner.getDiscoveredWorkload(request: request, options: options)
  }

  /// Lists a Discovered Workload in a host project and location, with a
  /// given resource URI.
  ///
  /// @Snippet(path: "AppHub_LookupDiscoveredWorkload")
  public func lookupDiscoveredWorkload(
    request: LookupDiscoveredWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse {
    try await self.inner.lookupDiscoveredWorkload(request: request, options: options)
  }

  /// Lists Workloads in an Application.
  ///
  /// @Snippet(path: "AppHub_ListWorkloads")
  public func listWorkloads(
    request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListWorkloadsResponse {
    try await self.inner.listWorkloads(request: request, options: options)
  }

  /// Lists Workloads in an Application.
  ///
  /// @Snippet(path: "AppHub_ListWorkloads")
  public func listWorkloads(
    byItem: ListWorkloadsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Workload, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListWorkloadsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listWorkloads(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a Workload in an Application.
  ///
  /// @Snippet(path: "AppHub_CreateWorkload")
  public func createWorkload(
    request: CreateWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createWorkload(request: request, options: options)
  }

  /// Creates a Workload in an Application.
  ///
  /// @Snippet(path: "AppHub_CreateWorkload")
  public func createWorkload(
    withPolling: CreateWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workload> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Workload>.State
      in
      return try op._extractStatus(Workload.self)
    }
    let rawOp = try await self.createWorkload(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Workload>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets a Workload in an Application.
  ///
  /// @Snippet(path: "AppHub_GetWorkload")
  public func getWorkload(
    request: GetWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.Workload {
    try await self.inner.getWorkload(request: request, options: options)
  }

  /// Updates a Workload in an Application.
  ///
  /// @Snippet(path: "AppHub_UpdateWorkload")
  public func updateWorkload(
    request: UpdateWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateWorkload(request: request, options: options)
  }

  /// Updates a Workload in an Application.
  ///
  /// @Snippet(path: "AppHub_UpdateWorkload")
  public func updateWorkload(
    withPolling: UpdateWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workload> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Workload>.State
      in
      return try op._extractStatus(Workload.self)
    }
    let rawOp = try await self.updateWorkload(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Workload>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a Workload from an Application.
  ///
  /// @Snippet(path: "AppHub_DeleteWorkload")
  public func deleteWorkload(
    request: DeleteWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteWorkload(request: request, options: options)
  }

  /// Deletes a Workload from an Application.
  ///
  /// @Snippet(path: "AppHub_DeleteWorkload")
  public func deleteWorkload(
    withPolling: DeleteWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteWorkload(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Applications in a host project and location.
  ///
  /// @Snippet(path: "AppHub_ListApplications")
  public func listApplications(
    request: ListApplicationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListApplicationsResponse {
    try await self.inner.listApplications(request: request, options: options)
  }

  /// Lists Applications in a host project and location.
  ///
  /// @Snippet(path: "AppHub_ListApplications")
  public func listApplications(
    byItem: ListApplicationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Application, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListApplicationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listApplications(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates an Application in a host project and location.
  ///
  /// @Snippet(path: "AppHub_CreateApplication")
  public func createApplication(
    request: CreateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createApplication(request: request, options: options)
  }

  /// Creates an Application in a host project and location.
  ///
  /// @Snippet(path: "AppHub_CreateApplication")
  public func createApplication(
    withPolling: CreateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Application>.State in
      return try op._extractStatus(Application.self)
    }
    let rawOp = try await self.createApplication(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets an Application in a host project and location.
  ///
  /// @Snippet(path: "AppHub_GetApplication")
  public func getApplication(
    request: GetApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.Application {
    try await self.inner.getApplication(request: request, options: options)
  }

  /// Updates an Application in a host project and location.
  ///
  /// @Snippet(path: "AppHub_UpdateApplication")
  public func updateApplication(
    request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateApplication(request: request, options: options)
  }

  /// Updates an Application in a host project and location.
  ///
  /// @Snippet(path: "AppHub_UpdateApplication")
  public func updateApplication(
    withPolling: UpdateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Application>.State in
      return try op._extractStatus(Application.self)
    }
    let rawOp = try await self.updateApplication(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an Application in a host project and location.
  ///
  /// @Snippet(path: "AppHub_DeleteApplication")
  public func deleteApplication(
    request: DeleteApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteApplication(request: request, options: options)
  }

  /// Deletes an Application in a host project and location.
  ///
  /// @Snippet(path: "AppHub_DeleteApplication")
  public func deleteApplication(
    withPolling: DeleteApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteApplication(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "AppHub_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "AppHub_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "AppHub_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "AppHub_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "AppHub_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "AppHub_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppHub_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppHub_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppHub_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppHub_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppHub_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AppHubClient`.
  ///
  /// To mock `AppHubClient` change your functions to receive
  /// `some AppHubProtocol` or `any AppHubProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AppHubProtocol {
    /// See `AppHubClient.lookupServiceProjectAttachment`.
    func lookupServiceProjectAttachment(request: LookupServiceProjectAttachmentRequest) async throws
      -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse

    /// See `AppHubClient.lookupServiceProjectAttachment`.
    func lookupServiceProjectAttachment(
      name: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse

    /// See `AppHubClient.listServiceProjectAttachments`.
    func listServiceProjectAttachments(request: ListServiceProjectAttachmentsRequest) async throws
      -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse

    /// See `AppHubClient.listServiceProjectAttachments`.
    func listServiceProjectAttachments(
      byItem: ListServiceProjectAttachmentsRequest
    ) -> any AsyncSequence<ServiceProjectAttachment, Swift.Error>

    /// See `AppHubClient.listServiceProjectAttachments`.
    func listServiceProjectAttachments(
      parent: Swift.String,
    ) -> any AsyncSequence<ServiceProjectAttachment, Swift.Error>

    /// See `AppHubClient.createServiceProjectAttachment`.
    func createServiceProjectAttachment(request: CreateServiceProjectAttachmentRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AppHubClient.createServiceProjectAttachment`.
    func createServiceProjectAttachment(withPolling: CreateServiceProjectAttachmentRequest)
      async throws -> any GoogleGax.PollableOperation<ServiceProjectAttachment>

    /// See `AppHubClient.createServiceProjectAttachment`.
    func createServiceProjectAttachment(
      parent: Swift.String,
      serviceProjectAttachment: ServiceProjectAttachment?,
      serviceProjectAttachmentId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<ServiceProjectAttachment>

    /// See `AppHubClient.getServiceProjectAttachment`.
    func getServiceProjectAttachment(request: GetServiceProjectAttachmentRequest) async throws
      -> GoogleCloudAppHubV1.ServiceProjectAttachment

    /// See `AppHubClient.getServiceProjectAttachment`.
    func getServiceProjectAttachment(
      name: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.ServiceProjectAttachment

    /// See `AppHubClient.deleteServiceProjectAttachment`.
    func deleteServiceProjectAttachment(request: DeleteServiceProjectAttachmentRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AppHubClient.deleteServiceProjectAttachment`.
    func deleteServiceProjectAttachment(withPolling: DeleteServiceProjectAttachmentRequest)
      async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppHubClient.deleteServiceProjectAttachment`.
    func deleteServiceProjectAttachment(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppHubClient.detachServiceProjectAttachment`.
    func detachServiceProjectAttachment(request: DetachServiceProjectAttachmentRequest) async throws
      -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse

    /// See `AppHubClient.detachServiceProjectAttachment`.
    func detachServiceProjectAttachment(
      name: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse

    /// See `AppHubClient.listDiscoveredServices`.
    func listDiscoveredServices(request: ListDiscoveredServicesRequest) async throws
      -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse

    /// See `AppHubClient.listDiscoveredServices`.
    func listDiscoveredServices(
      byItem: ListDiscoveredServicesRequest
    ) -> any AsyncSequence<DiscoveredService, Swift.Error>

    /// See `AppHubClient.listDiscoveredServices`.
    func listDiscoveredServices(
      parent: Swift.String,
    ) -> any AsyncSequence<DiscoveredService, Swift.Error>

    /// See `AppHubClient.getDiscoveredService`.
    func getDiscoveredService(request: GetDiscoveredServiceRequest) async throws
      -> GoogleCloudAppHubV1.DiscoveredService

    /// See `AppHubClient.getDiscoveredService`.
    func getDiscoveredService(
      name: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.DiscoveredService

    /// See `AppHubClient.lookupDiscoveredService`.
    func lookupDiscoveredService(request: LookupDiscoveredServiceRequest) async throws
      -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse

    /// See `AppHubClient.lookupDiscoveredService`.
    func lookupDiscoveredService(
      parent: Swift.String,
      uri: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse

    /// See `AppHubClient.listServices`.
    func listServices(request: ListServicesRequest) async throws
      -> GoogleCloudAppHubV1.ListServicesResponse

    /// See `AppHubClient.listServices`.
    func listServices(
      byItem: ListServicesRequest
    ) -> any AsyncSequence<Service, Swift.Error>

    /// See `AppHubClient.listServices`.
    func listServices(
      parent: Swift.String,
    ) -> any AsyncSequence<Service, Swift.Error>

    /// See `AppHubClient.createService`.
    func createService(request: CreateServiceRequest) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.createService`.
    func createService(withPolling: CreateServiceRequest) async throws -> any GoogleGax
      .PollableOperation<Service>

    /// See `AppHubClient.createService`.
    func createService(
      parent: Swift.String,
      service: Service?,
      serviceId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Service>

    /// See `AppHubClient.getService`.
    func getService(request: GetServiceRequest) async throws -> GoogleCloudAppHubV1.Service

    /// See `AppHubClient.getService`.
    func getService(
      name: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.Service

    /// See `AppHubClient.updateService`.
    func updateService(request: UpdateServiceRequest) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.updateService`.
    func updateService(withPolling: UpdateServiceRequest) async throws -> any GoogleGax
      .PollableOperation<Service>

    /// See `AppHubClient.updateService`.
    func updateService(
      service: Service?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Service>

    /// See `AppHubClient.deleteService`.
    func deleteService(request: DeleteServiceRequest) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.deleteService`.
    func deleteService(withPolling: DeleteServiceRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `AppHubClient.deleteService`.
    func deleteService(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppHubClient.listDiscoveredWorkloads`.
    func listDiscoveredWorkloads(request: ListDiscoveredWorkloadsRequest) async throws
      -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse

    /// See `AppHubClient.listDiscoveredWorkloads`.
    func listDiscoveredWorkloads(
      byItem: ListDiscoveredWorkloadsRequest
    ) -> any AsyncSequence<DiscoveredWorkload, Swift.Error>

    /// See `AppHubClient.listDiscoveredWorkloads`.
    func listDiscoveredWorkloads(
      parent: Swift.String,
    ) -> any AsyncSequence<DiscoveredWorkload, Swift.Error>

    /// See `AppHubClient.getDiscoveredWorkload`.
    func getDiscoveredWorkload(request: GetDiscoveredWorkloadRequest) async throws
      -> GoogleCloudAppHubV1.DiscoveredWorkload

    /// See `AppHubClient.getDiscoveredWorkload`.
    func getDiscoveredWorkload(
      name: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.DiscoveredWorkload

    /// See `AppHubClient.lookupDiscoveredWorkload`.
    func lookupDiscoveredWorkload(request: LookupDiscoveredWorkloadRequest) async throws
      -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse

    /// See `AppHubClient.lookupDiscoveredWorkload`.
    func lookupDiscoveredWorkload(
      parent: Swift.String,
      uri: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse

    /// See `AppHubClient.listWorkloads`.
    func listWorkloads(request: ListWorkloadsRequest) async throws
      -> GoogleCloudAppHubV1.ListWorkloadsResponse

    /// See `AppHubClient.listWorkloads`.
    func listWorkloads(
      byItem: ListWorkloadsRequest
    ) -> any AsyncSequence<Workload, Swift.Error>

    /// See `AppHubClient.listWorkloads`.
    func listWorkloads(
      parent: Swift.String,
    ) -> any AsyncSequence<Workload, Swift.Error>

    /// See `AppHubClient.createWorkload`.
    func createWorkload(request: CreateWorkloadRequest) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.createWorkload`.
    func createWorkload(withPolling: CreateWorkloadRequest) async throws -> any GoogleGax
      .PollableOperation<Workload>

    /// See `AppHubClient.createWorkload`.
    func createWorkload(
      parent: Swift.String,
      workload: Workload?,
      workloadId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Workload>

    /// See `AppHubClient.getWorkload`.
    func getWorkload(request: GetWorkloadRequest) async throws -> GoogleCloudAppHubV1.Workload

    /// See `AppHubClient.getWorkload`.
    func getWorkload(
      name: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.Workload

    /// See `AppHubClient.updateWorkload`.
    func updateWorkload(request: UpdateWorkloadRequest) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.updateWorkload`.
    func updateWorkload(withPolling: UpdateWorkloadRequest) async throws -> any GoogleGax
      .PollableOperation<Workload>

    /// See `AppHubClient.updateWorkload`.
    func updateWorkload(
      workload: Workload?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Workload>

    /// See `AppHubClient.deleteWorkload`.
    func deleteWorkload(request: DeleteWorkloadRequest) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.deleteWorkload`.
    func deleteWorkload(withPolling: DeleteWorkloadRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `AppHubClient.deleteWorkload`.
    func deleteWorkload(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppHubClient.listApplications`.
    func listApplications(request: ListApplicationsRequest) async throws
      -> GoogleCloudAppHubV1.ListApplicationsResponse

    /// See `AppHubClient.listApplications`.
    func listApplications(
      byItem: ListApplicationsRequest
    ) -> any AsyncSequence<Application, Swift.Error>

    /// See `AppHubClient.listApplications`.
    func listApplications(
      parent: Swift.String,
    ) -> any AsyncSequence<Application, Swift.Error>

    /// See `AppHubClient.createApplication`.
    func createApplication(request: CreateApplicationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AppHubClient.createApplication`.
    func createApplication(withPolling: CreateApplicationRequest) async throws -> any GoogleGax
      .PollableOperation<Application>

    /// See `AppHubClient.createApplication`.
    func createApplication(
      parent: Swift.String,
      application: Application?,
      applicationId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Application>

    /// See `AppHubClient.getApplication`.
    func getApplication(request: GetApplicationRequest) async throws
      -> GoogleCloudAppHubV1.Application

    /// See `AppHubClient.getApplication`.
    func getApplication(
      name: Swift.String,
    ) async throws -> GoogleCloudAppHubV1.Application

    /// See `AppHubClient.updateApplication`.
    func updateApplication(request: UpdateApplicationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AppHubClient.updateApplication`.
    func updateApplication(withPolling: UpdateApplicationRequest) async throws -> any GoogleGax
      .PollableOperation<Application>

    /// See `AppHubClient.updateApplication`.
    func updateApplication(
      application: Application?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Application>

    /// See `AppHubClient.deleteApplication`.
    func deleteApplication(request: DeleteApplicationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AppHubClient.deleteApplication`.
    func deleteApplication(withPolling: DeleteApplicationRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `AppHubClient.deleteApplication`.
    func deleteApplication(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppHubClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `AppHubClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AppHubClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `AppHubClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `AppHubClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `AppHubClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `AppHubClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `AppHubClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AppHubClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AppHubClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `AppHubClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `AppHubClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `AppHubClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `AppHubClient.lookupServiceProjectAttachment`.
    func lookupServiceProjectAttachment(
      request: LookupServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse

    /// See `AppHubClient.listServiceProjectAttachments`.
    func listServiceProjectAttachments(
      request: ListServiceProjectAttachmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse

    /// See `AppHubClient.listServiceProjectAttachments`.
    func listServiceProjectAttachments(
      byItem: ListServiceProjectAttachmentsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<ServiceProjectAttachment, Swift.Error>

    /// See `AppHubClient.createServiceProjectAttachment`.
    func createServiceProjectAttachment(
      request: CreateServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.createServiceProjectAttachment`.
    func createServiceProjectAttachment(
      withPolling: CreateServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ServiceProjectAttachment>

    /// See `AppHubClient.getServiceProjectAttachment`.
    func getServiceProjectAttachment(
      request: GetServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ServiceProjectAttachment

    /// See `AppHubClient.deleteServiceProjectAttachment`.
    func deleteServiceProjectAttachment(
      request: DeleteServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.deleteServiceProjectAttachment`.
    func deleteServiceProjectAttachment(
      withPolling: DeleteServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppHubClient.detachServiceProjectAttachment`.
    func detachServiceProjectAttachment(
      request: DetachServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse

    /// See `AppHubClient.listDiscoveredServices`.
    func listDiscoveredServices(
      request: ListDiscoveredServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse

    /// See `AppHubClient.listDiscoveredServices`.
    func listDiscoveredServices(
      byItem: ListDiscoveredServicesRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<DiscoveredService, Swift.Error>

    /// See `AppHubClient.getDiscoveredService`.
    func getDiscoveredService(
      request: GetDiscoveredServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.DiscoveredService

    /// See `AppHubClient.lookupDiscoveredService`.
    func lookupDiscoveredService(
      request: LookupDiscoveredServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse

    /// See `AppHubClient.listServices`.
    func listServices(
      request: ListServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListServicesResponse

    /// See `AppHubClient.listServices`.
    func listServices(
      byItem: ListServicesRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<Service, Swift.Error>

    /// See `AppHubClient.createService`.
    func createService(
      request: CreateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.createService`.
    func createService(
      withPolling: CreateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Service>

    /// See `AppHubClient.getService`.
    func getService(
      request: GetServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.Service

    /// See `AppHubClient.updateService`.
    func updateService(
      request: UpdateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.updateService`.
    func updateService(
      withPolling: UpdateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Service>

    /// See `AppHubClient.deleteService`.
    func deleteService(
      request: DeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.deleteService`.
    func deleteService(
      withPolling: DeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppHubClient.listDiscoveredWorkloads`.
    func listDiscoveredWorkloads(
      request: ListDiscoveredWorkloadsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse

    /// See `AppHubClient.listDiscoveredWorkloads`.
    func listDiscoveredWorkloads(
      byItem: ListDiscoveredWorkloadsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<DiscoveredWorkload, Swift.Error>

    /// See `AppHubClient.getDiscoveredWorkload`.
    func getDiscoveredWorkload(
      request: GetDiscoveredWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.DiscoveredWorkload

    /// See `AppHubClient.lookupDiscoveredWorkload`.
    func lookupDiscoveredWorkload(
      request: LookupDiscoveredWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse

    /// See `AppHubClient.listWorkloads`.
    func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListWorkloadsResponse

    /// See `AppHubClient.listWorkloads`.
    func listWorkloads(
      byItem: ListWorkloadsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<Workload, Swift.Error>

    /// See `AppHubClient.createWorkload`.
    func createWorkload(
      request: CreateWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.createWorkload`.
    func createWorkload(
      withPolling: CreateWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Workload>

    /// See `AppHubClient.getWorkload`.
    func getWorkload(
      request: GetWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.Workload

    /// See `AppHubClient.updateWorkload`.
    func updateWorkload(
      request: UpdateWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.updateWorkload`.
    func updateWorkload(
      withPolling: UpdateWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Workload>

    /// See `AppHubClient.deleteWorkload`.
    func deleteWorkload(
      request: DeleteWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.deleteWorkload`.
    func deleteWorkload(
      withPolling: DeleteWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppHubClient.listApplications`.
    func listApplications(
      request: ListApplicationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListApplicationsResponse

    /// See `AppHubClient.listApplications`.
    func listApplications(
      byItem: ListApplicationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<Application, Swift.Error>

    /// See `AppHubClient.createApplication`.
    func createApplication(
      request: CreateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.createApplication`.
    func createApplication(
      withPolling: CreateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Application>

    /// See `AppHubClient.getApplication`.
    func getApplication(
      request: GetApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.Application

    /// See `AppHubClient.updateApplication`.
    func updateApplication(
      request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.updateApplication`.
    func updateApplication(
      withPolling: UpdateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Application>

    /// See `AppHubClient.deleteApplication`.
    func deleteApplication(
      request: DeleteApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppHubClient.deleteApplication`.
    func deleteApplication(
      withPolling: DeleteApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppHubClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `AppHubClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AppHubClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `AppHubClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AppHubClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AppHubClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `AppHubClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AppHubClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AppHubClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AppHubClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AppHubProtocol {
  public func lookupServiceProjectAttachment(request: LookupServiceProjectAttachmentRequest)
    async throws -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse
  {
    try await self.lookupServiceProjectAttachment(request: request, options: .init())
  }

  public func lookupServiceProjectAttachment(
    request: LookupServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func lookupServiceProjectAttachment(
    name: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse {
    let request = LookupServiceProjectAttachmentRequest().with {
      $0.name = name
    }
    return try await self.lookupServiceProjectAttachment(request: request)
  }

  public func listServiceProjectAttachments(request: ListServiceProjectAttachmentsRequest)
    async throws -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse
  {
    try await self.listServiceProjectAttachments(request: request, options: .init())
  }

  public func listServiceProjectAttachments(
    request: ListServiceProjectAttachmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServiceProjectAttachments(
    byItem: ListServiceProjectAttachmentsRequest
  ) -> any AsyncSequence<ServiceProjectAttachment, Swift.Error> {
    self.listServiceProjectAttachments(byItem: byItem, options: .init())
  }

  public func listServiceProjectAttachments(
    byItem: ListServiceProjectAttachmentsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ServiceProjectAttachment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listServiceProjectAttachments(
    parent: Swift.String,
  ) -> any AsyncSequence<ServiceProjectAttachment, Swift.Error> {
    let request = ListServiceProjectAttachmentsRequest().with {
      $0.parent = parent
    }
    return self.listServiceProjectAttachments(byItem: request)
  }

  public func createServiceProjectAttachment(request: CreateServiceProjectAttachmentRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.createServiceProjectAttachment(request: request, options: .init())
  }

  public func createServiceProjectAttachment(
    request: CreateServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createServiceProjectAttachment(withPolling: CreateServiceProjectAttachmentRequest)
    async throws -> any GoogleGax.PollableOperation<ServiceProjectAttachment>
  {
    try await self.createServiceProjectAttachment(withPolling: withPolling, options: .init())
  }

  public func createServiceProjectAttachment(
    withPolling: CreateServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ServiceProjectAttachment> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ServiceProjectAttachment>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createServiceProjectAttachment(
    parent: Swift.String,
    serviceProjectAttachment: ServiceProjectAttachment?,
    serviceProjectAttachmentId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<ServiceProjectAttachment> {
    let request = CreateServiceProjectAttachmentRequest().with {
      $0.parent = parent
      $0.serviceProjectAttachment = serviceProjectAttachment
      $0.serviceProjectAttachmentId = serviceProjectAttachmentId
    }
    return try await self.createServiceProjectAttachment(withPolling: request)
  }

  public func getServiceProjectAttachment(request: GetServiceProjectAttachmentRequest) async throws
    -> GoogleCloudAppHubV1.ServiceProjectAttachment
  {
    try await self.getServiceProjectAttachment(request: request, options: .init())
  }

  public func getServiceProjectAttachment(
    request: GetServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ServiceProjectAttachment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getServiceProjectAttachment(
    name: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.ServiceProjectAttachment {
    let request = GetServiceProjectAttachmentRequest().with {
      $0.name = name
    }
    return try await self.getServiceProjectAttachment(request: request)
  }

  public func deleteServiceProjectAttachment(request: DeleteServiceProjectAttachmentRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteServiceProjectAttachment(request: request, options: .init())
  }

  public func deleteServiceProjectAttachment(
    request: DeleteServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServiceProjectAttachment(withPolling: DeleteServiceProjectAttachmentRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteServiceProjectAttachment(withPolling: withPolling, options: .init())
  }

  public func deleteServiceProjectAttachment(
    withPolling: DeleteServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteServiceProjectAttachment(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteServiceProjectAttachmentRequest().with {
      $0.name = name
    }
    return try await self.deleteServiceProjectAttachment(withPolling: request)
  }

  public func detachServiceProjectAttachment(request: DetachServiceProjectAttachmentRequest)
    async throws -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse
  {
    try await self.detachServiceProjectAttachment(request: request, options: .init())
  }

  public func detachServiceProjectAttachment(
    request: DetachServiceProjectAttachmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func detachServiceProjectAttachment(
    name: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse {
    let request = DetachServiceProjectAttachmentRequest().with {
      $0.name = name
    }
    return try await self.detachServiceProjectAttachment(request: request)
  }

  public func listDiscoveredServices(request: ListDiscoveredServicesRequest) async throws
    -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse
  {
    try await self.listDiscoveredServices(request: request, options: .init())
  }

  public func listDiscoveredServices(
    request: ListDiscoveredServicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listDiscoveredServices(
    byItem: ListDiscoveredServicesRequest
  ) -> any AsyncSequence<DiscoveredService, Swift.Error> {
    self.listDiscoveredServices(byItem: byItem, options: .init())
  }

  public func listDiscoveredServices(
    byItem: ListDiscoveredServicesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<DiscoveredService, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDiscoveredServices(
    parent: Swift.String,
  ) -> any AsyncSequence<DiscoveredService, Swift.Error> {
    let request = ListDiscoveredServicesRequest().with {
      $0.parent = parent
    }
    return self.listDiscoveredServices(byItem: request)
  }

  public func getDiscoveredService(request: GetDiscoveredServiceRequest) async throws
    -> GoogleCloudAppHubV1.DiscoveredService
  {
    try await self.getDiscoveredService(request: request, options: .init())
  }

  public func getDiscoveredService(
    request: GetDiscoveredServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.DiscoveredService {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDiscoveredService(
    name: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.DiscoveredService {
    let request = GetDiscoveredServiceRequest().with {
      $0.name = name
    }
    return try await self.getDiscoveredService(request: request)
  }

  public func lookupDiscoveredService(request: LookupDiscoveredServiceRequest) async throws
    -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse
  {
    try await self.lookupDiscoveredService(request: request, options: .init())
  }

  public func lookupDiscoveredService(
    request: LookupDiscoveredServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func lookupDiscoveredService(
    parent: Swift.String,
    uri: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse {
    let request = LookupDiscoveredServiceRequest().with {
      $0.parent = parent
      $0.uri = uri
    }
    return try await self.lookupDiscoveredService(request: request)
  }

  public func listServices(request: ListServicesRequest) async throws
    -> GoogleCloudAppHubV1.ListServicesResponse
  {
    try await self.listServices(request: request, options: .init())
  }

  public func listServices(
    request: ListServicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListServicesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServices(
    byItem: ListServicesRequest
  ) -> any AsyncSequence<Service, Swift.Error> {
    self.listServices(byItem: byItem, options: .init())
  }

  public func listServices(
    byItem: ListServicesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Service, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListServicesResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listServices(
    parent: Swift.String,
  ) -> any AsyncSequence<Service, Swift.Error> {
    let request = ListServicesRequest().with {
      $0.parent = parent
    }
    return self.listServices(byItem: request)
  }

  public func createService(request: CreateServiceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createService(request: request, options: .init())
  }

  public func createService(
    request: CreateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createService(withPolling: CreateServiceRequest) async throws -> any GoogleGax
    .PollableOperation<Service>
  {
    try await self.createService(withPolling: withPolling, options: .init())
  }

  public func createService(
    withPolling: CreateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Service> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Service>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createService(
    parent: Swift.String,
    service: Service?,
    serviceId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Service> {
    let request = CreateServiceRequest().with {
      $0.parent = parent
      $0.service = service
      $0.serviceId = serviceId
    }
    return try await self.createService(withPolling: request)
  }

  public func getService(request: GetServiceRequest) async throws -> GoogleCloudAppHubV1.Service {
    try await self.getService(request: request, options: .init())
  }

  public func getService(
    request: GetServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.Service {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getService(
    name: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.Service {
    let request = GetServiceRequest().with {
      $0.name = name
    }
    return try await self.getService(request: request)
  }

  public func updateService(request: UpdateServiceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateService(request: request, options: .init())
  }

  public func updateService(
    request: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateService(withPolling: UpdateServiceRequest) async throws -> any GoogleGax
    .PollableOperation<Service>
  {
    try await self.updateService(withPolling: withPolling, options: .init())
  }

  public func updateService(
    withPolling: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Service> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Service>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateService(
    service: Service?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Service> {
    let request = UpdateServiceRequest().with {
      $0.service = service
      $0.updateMask = updateMask
    }
    return try await self.updateService(withPolling: request)
  }

  public func deleteService(request: DeleteServiceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteService(request: request, options: .init())
  }

  public func deleteService(
    request: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteService(withPolling: DeleteServiceRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteService(withPolling: withPolling, options: .init())
  }

  public func deleteService(
    withPolling: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteService(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteServiceRequest().with {
      $0.name = name
    }
    return try await self.deleteService(withPolling: request)
  }

  public func listDiscoveredWorkloads(request: ListDiscoveredWorkloadsRequest) async throws
    -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse
  {
    try await self.listDiscoveredWorkloads(request: request, options: .init())
  }

  public func listDiscoveredWorkloads(
    request: ListDiscoveredWorkloadsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listDiscoveredWorkloads(
    byItem: ListDiscoveredWorkloadsRequest
  ) -> any AsyncSequence<DiscoveredWorkload, Swift.Error> {
    self.listDiscoveredWorkloads(byItem: byItem, options: .init())
  }

  public func listDiscoveredWorkloads(
    byItem: ListDiscoveredWorkloadsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<DiscoveredWorkload, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDiscoveredWorkloads(
    parent: Swift.String,
  ) -> any AsyncSequence<DiscoveredWorkload, Swift.Error> {
    let request = ListDiscoveredWorkloadsRequest().with {
      $0.parent = parent
    }
    return self.listDiscoveredWorkloads(byItem: request)
  }

  public func getDiscoveredWorkload(request: GetDiscoveredWorkloadRequest) async throws
    -> GoogleCloudAppHubV1.DiscoveredWorkload
  {
    try await self.getDiscoveredWorkload(request: request, options: .init())
  }

  public func getDiscoveredWorkload(
    request: GetDiscoveredWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.DiscoveredWorkload {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDiscoveredWorkload(
    name: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.DiscoveredWorkload {
    let request = GetDiscoveredWorkloadRequest().with {
      $0.name = name
    }
    return try await self.getDiscoveredWorkload(request: request)
  }

  public func lookupDiscoveredWorkload(request: LookupDiscoveredWorkloadRequest) async throws
    -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse
  {
    try await self.lookupDiscoveredWorkload(request: request, options: .init())
  }

  public func lookupDiscoveredWorkload(
    request: LookupDiscoveredWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func lookupDiscoveredWorkload(
    parent: Swift.String,
    uri: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse {
    let request = LookupDiscoveredWorkloadRequest().with {
      $0.parent = parent
      $0.uri = uri
    }
    return try await self.lookupDiscoveredWorkload(request: request)
  }

  public func listWorkloads(request: ListWorkloadsRequest) async throws
    -> GoogleCloudAppHubV1.ListWorkloadsResponse
  {
    try await self.listWorkloads(request: request, options: .init())
  }

  public func listWorkloads(
    request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListWorkloadsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listWorkloads(
    byItem: ListWorkloadsRequest
  ) -> any AsyncSequence<Workload, Swift.Error> {
    self.listWorkloads(byItem: byItem, options: .init())
  }

  public func listWorkloads(
    byItem: ListWorkloadsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Workload, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListWorkloadsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkloads(
    parent: Swift.String,
  ) -> any AsyncSequence<Workload, Swift.Error> {
    let request = ListWorkloadsRequest().with {
      $0.parent = parent
    }
    return self.listWorkloads(byItem: request)
  }

  public func createWorkload(request: CreateWorkloadRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createWorkload(request: request, options: .init())
  }

  public func createWorkload(
    request: CreateWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createWorkload(withPolling: CreateWorkloadRequest) async throws -> any GoogleGax
    .PollableOperation<Workload>
  {
    try await self.createWorkload(withPolling: withPolling, options: .init())
  }

  public func createWorkload(
    withPolling: CreateWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workload> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Workload>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createWorkload(
    parent: Swift.String,
    workload: Workload?,
    workloadId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Workload> {
    let request = CreateWorkloadRequest().with {
      $0.parent = parent
      $0.workload = workload
      $0.workloadId = workloadId
    }
    return try await self.createWorkload(withPolling: request)
  }

  public func getWorkload(request: GetWorkloadRequest) async throws -> GoogleCloudAppHubV1.Workload
  {
    try await self.getWorkload(request: request, options: .init())
  }

  public func getWorkload(
    request: GetWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.Workload {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getWorkload(
    name: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.Workload {
    let request = GetWorkloadRequest().with {
      $0.name = name
    }
    return try await self.getWorkload(request: request)
  }

  public func updateWorkload(request: UpdateWorkloadRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateWorkload(request: request, options: .init())
  }

  public func updateWorkload(
    request: UpdateWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateWorkload(withPolling: UpdateWorkloadRequest) async throws -> any GoogleGax
    .PollableOperation<Workload>
  {
    try await self.updateWorkload(withPolling: withPolling, options: .init())
  }

  public func updateWorkload(
    withPolling: UpdateWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Workload> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Workload>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateWorkload(
    workload: Workload?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Workload> {
    let request = UpdateWorkloadRequest().with {
      $0.workload = workload
      $0.updateMask = updateMask
    }
    return try await self.updateWorkload(withPolling: request)
  }

  public func deleteWorkload(request: DeleteWorkloadRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteWorkload(request: request, options: .init())
  }

  public func deleteWorkload(
    request: DeleteWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteWorkload(withPolling: DeleteWorkloadRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteWorkload(withPolling: withPolling, options: .init())
  }

  public func deleteWorkload(
    withPolling: DeleteWorkloadRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteWorkload(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteWorkloadRequest().with {
      $0.name = name
    }
    return try await self.deleteWorkload(withPolling: request)
  }

  public func listApplications(request: ListApplicationsRequest) async throws
    -> GoogleCloudAppHubV1.ListApplicationsResponse
  {
    try await self.listApplications(request: request, options: .init())
  }

  public func listApplications(
    request: ListApplicationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.ListApplicationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listApplications(
    byItem: ListApplicationsRequest
  ) -> any AsyncSequence<Application, Swift.Error> {
    self.listApplications(byItem: byItem, options: .init())
  }

  public func listApplications(
    byItem: ListApplicationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Application, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppHubV1.ListApplicationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listApplications(
    parent: Swift.String,
  ) -> any AsyncSequence<Application, Swift.Error> {
    let request = ListApplicationsRequest().with {
      $0.parent = parent
    }
    return self.listApplications(byItem: request)
  }

  public func createApplication(request: CreateApplicationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createApplication(request: request, options: .init())
  }

  public func createApplication(
    request: CreateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createApplication(withPolling: CreateApplicationRequest) async throws -> any GoogleGax
    .PollableOperation<Application>
  {
    try await self.createApplication(withPolling: withPolling, options: .init())
  }

  public func createApplication(
    withPolling: CreateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createApplication(
    parent: Swift.String,
    application: Application?,
    applicationId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let request = CreateApplicationRequest().with {
      $0.parent = parent
      $0.application = application
      $0.applicationId = applicationId
    }
    return try await self.createApplication(withPolling: request)
  }

  public func getApplication(request: GetApplicationRequest) async throws
    -> GoogleCloudAppHubV1.Application
  {
    try await self.getApplication(request: request, options: .init())
  }

  public func getApplication(
    request: GetApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudAppHubV1.Application {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getApplication(
    name: Swift.String,
  ) async throws -> GoogleCloudAppHubV1.Application {
    let request = GetApplicationRequest().with {
      $0.name = name
    }
    return try await self.getApplication(request: request)
  }

  public func updateApplication(request: UpdateApplicationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateApplication(request: request, options: .init())
  }

  public func updateApplication(
    request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateApplication(withPolling: UpdateApplicationRequest) async throws -> any GoogleGax
    .PollableOperation<Application>
  {
    try await self.updateApplication(withPolling: withPolling, options: .init())
  }

  public func updateApplication(
    withPolling: UpdateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateApplication(
    application: Application?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let request = UpdateApplicationRequest().with {
      $0.application = application
      $0.updateMask = updateMask
    }
    return try await self.updateApplication(withPolling: request)
  }

  public func deleteApplication(request: DeleteApplicationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteApplication(request: request, options: .init())
  }

  public func deleteApplication(
    request: DeleteApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteApplication(withPolling: DeleteApplicationRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteApplication(withPolling: withPolling, options: .init())
  }

  public func deleteApplication(
    withPolling: DeleteApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteApplication(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteApplicationRequest().with {
      $0.name = name
    }
    return try await self.deleteApplication(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
