// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol AppHubStub {
    func lookupServiceProjectAttachment(
      request: LookupServiceProjectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.LookupServiceProjectAttachmentResponse

    func listServiceProjectAttachments(
      request: ListServiceProjectAttachmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListServiceProjectAttachmentsResponse

    func createServiceProjectAttachment(
      request: CreateServiceProjectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getServiceProjectAttachment(
      request: GetServiceProjectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ServiceProjectAttachment

    func deleteServiceProjectAttachment(
      request: DeleteServiceProjectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func detachServiceProjectAttachment(
      request: DetachServiceProjectAttachmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.DetachServiceProjectAttachmentResponse

    func listDiscoveredServices(
      request: ListDiscoveredServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListDiscoveredServicesResponse

    func getDiscoveredService(
      request: GetDiscoveredServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.DiscoveredService

    func lookupDiscoveredService(
      request: LookupDiscoveredServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredServiceResponse

    func listServices(
      request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListServicesResponse

    func createService(
      request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getService(
      request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.Service

    func updateService(
      request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteService(
      request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listDiscoveredWorkloads(
      request: ListDiscoveredWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListDiscoveredWorkloadsResponse

    func getDiscoveredWorkload(
      request: GetDiscoveredWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.DiscoveredWorkload

    func lookupDiscoveredWorkload(
      request: LookupDiscoveredWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.LookupDiscoveredWorkloadResponse

    func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListWorkloadsResponse

    func createWorkload(
      request: CreateWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getWorkload(
      request: GetWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.Workload

    func updateWorkload(
      request: UpdateWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteWorkload(
      request: DeleteWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listApplications(
      request: ListApplicationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.ListApplicationsResponse

    func createApplication(
      request: CreateApplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getApplication(
      request: GetApplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppHubV1.Application

    func updateApplication(
      request: UpdateApplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteApplication(
      request: DeleteApplicationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
