// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Consumer provided attributes.
public struct Attributes: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. User-defined criticality information.
  public var criticality: Criticality? = nil

  /// Optional. User-defined environment information.
  public var environment: Environment? = nil

  /// Optional. Developer team that owns development and coding.
  public var developerOwners: [ContactInfo] = []

  /// Optional. Operator team that ensures runtime and operations.
  public var operatorOwners: [ContactInfo] = []

  /// Optional. Business team that ensures user needs are met and value is
  /// delivered
  public var businessOwners: [ContactInfo] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Attributes`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Attributes().with { $0.criticality = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let criticality = CodingKeys(stringValue: "criticality")
    static let environment = CodingKeys(stringValue: "environment")
    static let developerOwners = CodingKeys(stringValue: "developerOwners")
    static let operatorOwners = CodingKeys(stringValue: "operatorOwners")
    static let businessOwners = CodingKeys(stringValue: "businessOwners")

    static let _knownKeys: Set<Swift.String> = [
      "criticality",
      "environment",
      "developerOwners",
      "operatorOwners",
      "businessOwners",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.criticality = try container.decodeIfPresent(Criticality.self, forKey: .criticality)
    self.environment = try container.decodeIfPresent(Environment.self, forKey: .environment)
    if let value = try container.decodeIfPresent([ContactInfo].self, forKey: .developerOwners) {
      self.developerOwners = value
    }
    if let value = try container.decodeIfPresent([ContactInfo].self, forKey: .operatorOwners) {
      self.operatorOwners = value
    }
    if let value = try container.decodeIfPresent([ContactInfo].self, forKey: .businessOwners) {
      self.businessOwners = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.criticality, forKey: .criticality)
    try container.encodeIfPresent(self.environment, forKey: .environment)
    try container.encode(self.developerOwners, forKey: .developerOwners)
    try container.encode(self.operatorOwners, forKey: .operatorOwners)
    try container.encode(self.businessOwners, forKey: .businessOwners)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apphub.v1.Attributes"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
