// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Consumer provided attributes.
public struct Attributes: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. User-defined criticality information.
  public var criticality: Criticality? = nil

  /// Optional. User-defined environment information.
  public var environment: Environment? = nil

  /// Optional. Developer team that owns development and coding.
  public var developerOwners: [ContactInfo] = []

  /// Optional. Operator team that ensures runtime and operations.
  public var operatorOwners: [ContactInfo] = []

  /// Optional. Business team that ensures user needs are met and value is
  /// delivered
  public var businessOwners: [ContactInfo] = []

  /// Initialize a new instance of `Attributes`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Attributes().with { $0.criticality = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apphub.v1.Attributes"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
