// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// DiscoveredService is a network or API interface that exposes some
/// functionality to clients for consumption over the network. A discovered
/// service can be registered to a App Hub service.
public struct DiscoveredService: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the discovered service. Format:
  /// `"projects/{host-project-id}/locations/{location}/discoveredServices/{uuid}"`
  public var name: Swift.String = Swift.String()

  /// Output only. Reference to an underlying networking resource that can
  /// comprise a Service. These are immutable.
  public var serviceReference: ServiceReference? = nil

  /// Output only. Properties of an underlying compute resource that can comprise
  /// a Service. These are immutable.
  public var serviceProperties: ServiceProperties? = nil

  /// Initialize a new instance of `DiscoveredService`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveredService().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apphub.v1.DiscoveredService"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
