// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DiscoveredService is a network or API interface that exposes some
/// functionality to clients for consumption over the network. A discovered
/// service can be registered to a App Hub service.
public struct DiscoveredService: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the discovered service. Format:
  /// `"projects/{host-project-id}/locations/{location}/discoveredServices/{uuid}"`
  public var name: Swift.String = Swift.String()

  /// Output only. Reference to an underlying networking resource that can
  /// comprise a Service. These are immutable.
  public var serviceReference: ServiceReference? = nil

  /// Output only. Properties of an underlying compute resource that can comprise
  /// a Service. These are immutable.
  public var serviceProperties: ServiceProperties? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiscoveredService`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveredService().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let serviceReference = CodingKeys(stringValue: "serviceReference")
    static let serviceProperties = CodingKeys(stringValue: "serviceProperties")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "serviceReference",
      "serviceProperties",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.serviceReference = try container.decodeIfPresent(
      ServiceReference.self, forKey: .serviceReference)
    self.serviceProperties = try container.decodeIfPresent(
      ServiceProperties.self, forKey: .serviceProperties)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.serviceReference, forKey: .serviceReference)
    try container.encodeIfPresent(self.serviceProperties, forKey: .serviceProperties)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apphub.v1.DiscoveredService"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
