// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Properties of an underlying cloud resource that can comprise a Service.
public struct ServiceProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The service project identifier that the underlying cloud
  /// resource resides in.
  public var gcpProject: Swift.String = Swift.String()

  /// Output only. The location that the underlying resource resides in, for
  /// example, us-west1.
  public var location: Swift.String = Swift.String()

  /// Output only. The location that the underlying resource resides in if it is
  /// zonal, for example, us-west1-a).
  public var zone: Swift.String = Swift.String()

  /// Output only. The type of the service.
  public var functionalType: FunctionalType? = nil

  /// Output only. The registration type of the service.
  public var registrationType: RegistrationType? = nil

  /// Output only. Additional metadata specific to the resource type.
  /// The key is a string that identifies the type of metadata and the value is
  /// the metadata contents specific to that type.
  /// Key format: `apphub.googleapis.com/{metadataType}`
  public var extendedMetadata: [Swift.String: ExtendedMetadata] = [:]

  /// Output only. The identity associated with the service.
  public var identity: Identity? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServiceProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceProperties().with { $0.gcpProject = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcpProject = CodingKeys(stringValue: "gcpProject")
    static let location = CodingKeys(stringValue: "location")
    static let zone = CodingKeys(stringValue: "zone")
    static let functionalType = CodingKeys(stringValue: "functionalType")
    static let registrationType = CodingKeys(stringValue: "registrationType")
    static let extendedMetadata = CodingKeys(stringValue: "extendedMetadata")
    static let identity = CodingKeys(stringValue: "identity")

    static let _knownKeys: Set<Swift.String> = [
      "gcpProject",
      "location",
      "zone",
      "functionalType",
      "registrationType",
      "extendedMetadata",
      "identity",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcpProject) {
      self.gcpProject = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .zone) {
      self.zone = value
    }
    self.functionalType = try container.decodeIfPresent(
      FunctionalType.self, forKey: .functionalType)
    self.registrationType = try container.decodeIfPresent(
      RegistrationType.self, forKey: .registrationType)
    if let value = try container.decodeIfPresent(
      [Swift.String: ExtendedMetadata].self, forKey: .extendedMetadata)
    {
      self.extendedMetadata = value
    }
    self.identity = try container.decodeIfPresent(Identity.self, forKey: .identity)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.gcpProject, forKey: .gcpProject)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.zone, forKey: .zone)
    try container.encodeIfPresent(self.functionalType, forKey: .functionalType)
    try container.encodeIfPresent(self.registrationType, forKey: .registrationType)
    try container.encode(self.extendedMetadata, forKey: .extendedMetadata)
    try container.encodeIfPresent(self.identity, forKey: .identity)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ServiceProperties`: `"type.googleapis.com/google.cloud.apphub.v1.ServiceProperties"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apphub.v1.ServiceProperties"
  }

  /// Initialize an instance of `ServiceProperties` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.apphub.v1.ServiceProperties"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ServiceProperties` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
